#!/usr/bin/env bash
set -e

if [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "Usage:"
    echo "  gh q get <repo>           ... Clone a repository into ~/ghq/github.com"
    echo "  gh q list                 ... List all repositories in ~/ghq/github.com"
    echo "  gh q -- <command>         ... Search via fzf and run <command> in the selected directory"
    echo "  gh q <command>            ... Search via fzf and run <command> with selected directory as argument"
    exit 0

# gh q get
elif [ "$1" == "get" ]; then
    repo_name=$(echo "$2" | sed -e 's/.*github.com[:\/]//' -e 's/\.git$//' -e 's/\/$//')
    repo_path="$HOME/ghq/github.com/${repo_name}"

    gh repo clone "$2" "$repo_path"


# gh q list
elif [ "$1" == "list" ]; then
    fd --max-depth 3 --min-depth 3 --type d . ~/ghq || find ~/ghq -maxdepth 3 -mindepth 3 -type d


# gh q -- <command>
elif [ "$1" == "--" ]; then
    shift  # Remove the "--" from arguments
    selected_dir=$(gh q list | fzf)
    if [ -n "$selected_dir" ]; then
        cd "$selected_dir"
        if [ $# -eq 0 ]; then
            exec "$SHELL"
        else
            exec "$@"
        fi
    fi

# gh q <command>
else
    selected_dir=$(gh q list | fzf)
    if [ -n "$selected_dir" ]; then
        exec "$@" "$selected_dir"
    fi
fi
